import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useState } from "react";
import { trpc } from "../utils/trpc";

// https://www.ted.com/talks/tawanda_kanhema_my_journey_mapping_the_uncharted_world/transcript
// https://www.ted.com/talks/tawanda_kanhema_my_journey_mapping_the_uncharted_world
function splitTedLink(link: string) {
  if (link.startsWith("https://www.ted.com/talks/")) {
    return link.split("talks/")[1]?.split("/")[0];
  } else {
    return link;
  }
}
const Home: NextPage = () => {
  const [link, setLink] = useState("");

  const router = useRouter();
  function handleLoad() {
    const title = splitTedLink(link);
    if (title) {
      // go to talk/[title]
      router.push(`/talk/${title}`);
    }
  }
  return (
    <>
      <Head>
        <title>Ted transcript</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="home h-screen w-screen">
        <div className="bg-gradient-to-t from-[#ffffffEF] to-[#ffffffAA] flex flex-col items-center justify-center h-full w-full">
          <h3 className="mb-10 max-w-4xl text-center text-3xl font-bold text-gray-600 md:mx-auto md:px-20 md:text-6xl md:leading-[1.2]">
            Type the <span className="font-extrabold text-[#e72b1e]">TED</span>
            &nbsp;
            <span className="underline">link</span> or{" "}
            <span className="underline">title</span>&nbsp; below to get your
            transcript 🚀
          </h3>

          <div className="search flex w-screen justify-center">
            <input
              className="text-main-600 caret-main-500 shadow-main-300/90 placeholder:text-main-400 inline-block h-[2.8rem] w-[70%] max-w-2xl overflow-hidden rounded-lg border-[1px] bg-gray-100 px-5 text-center text-lg font-medium outline-none transition-all duration-300 placeholder:select-none placeholder:font-normal focus:border-gray-200 focus:bg-white focus:shadow-[0_0_1.5rem_var(--tw-shadow-color)]"
              placeholder="link or title"
              onChange={(e) => setLink(e.target.value)}
              value={link}
            ></input>
            <button
              onClick={handleLoad}
              className="ml-2 inline-flex h-[2.8rem] items-center rounded-md bg-gray-400 px-4 py-2 text-sm font-medium text-white hover:bg-indigo-600"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                className="mr-2 h-5 w-5"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  stroke-width="2"
                  d="M3 10h10a8 8 0 018 8v2M3 10l6 6m-6-6l6-6"
                />
              </svg>
              Go
            </button>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
