import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useEffect } from "react";
import Talk from "../components/Talk";

import { trpc } from "../utils/trpc";

const Home: NextPage = () => {

  const {data, isFetching, refetch} = trpc.example.bilingualDetail.useQuery(
    {id: 'mark_pollock_and_simone_george_a_love_letter_to_realism_in_a_time_of_grief'},
    {enabled: false, cacheTime: Infinity}
    )
  useEffect(() => {
    refetch()
  }, [refetch])
  if (isFetching) {
    return <div>Fetching...</div>
  }
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {data && <Talk data={data} />}
    </>
  );
};

export default Home;
