import { type NextPage } from "next";
import { useRouter } from "next/router";
import Head from "next/head";
import { useEffect } from "react";
import Talk from "../../components/Talk";
import { trpc } from "../../utils/trpc";

const TalkPage: NextPage = () => {
  const router = useRouter();
  const talkId = router.query.talkId as string;

  const { data, isFetching, refetch } = trpc.example.bilingualDetail.useQuery(
    { id: talkId as string },
    { enabled: false, cacheTime: Infinity }
  );

  useEffect(() => {
    if (talkId) {
      refetch();
    }
  }, [refetch, talkId]);

  if (!talkId) {
    return <div>Please provide a talkId.</div>;
  }
  if (isFetching) {
    return <div>Fetching...</div>;
  }
  return (
    <>
      <Head>
        <title></title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="m-2">{data && <Talk data={data} />}</div>
    </>
  );
};

export default TalkPage;
